# Generated by Django 4.2.17 on 2024-12-18 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('Specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty_bot.specialist', verbose_name='Специалисты')),
            ],
        ),
    ]
