# Generated by Django 4.2.17 on 2024-12-18 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_bot', '0002_salones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'клиент', 'verbose_name_plural': 'Имя клиента'},
        ),
        migrations.AlterModelOptions(
            name='salones',
            options={'verbose_name': 'салон', 'verbose_name_plural': 'Салон'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'запись', 'verbose_name_plural': 'Запись'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='specialist',
            options={'verbose_name': 'специалист', 'verbose_name_plural': 'Специалтст'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'слот', 'verbose_name_plural': 'Временной слот'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='salone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beauty_bot.salones', verbose_name='Салон'),
        ),
    ]
