# Generated by Django 4.2.17 on 2024-12-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_bot', '0003_alter_clients_options_alter_salones_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialist',
            options={'verbose_name': 'специалист', 'verbose_name_plural': 'Специалист'},
        ),
        migrations.AddField(
            model_name='salones',
            name='addres',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес'),
        ),
    ]
