# Generated by Django 4.2.17 on 2024-12-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_bot', '0004_alter_specialist_options_salones_addres'),
    ]

    operations = [
        migrations.AddField(
            model_name='salones',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, verbose_name='Телефон салона'),
        ),
    ]
