# Generated by Django 4.2.17 on 2024-12-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_bot', '0005_salones_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salones',
            name='Specialist',
        ),
        migrations.AddField(
            model_name='salones',
            name='Specialist',
            field=models.ManyToManyField(to='beauty_bot.specialist', verbose_name='Специалисты'),
        ),
    ]
