# Generated by Django 4.2.17 on 2024-12-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_bot', '0006_remove_salones_specialist_salones_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salones',
            name='phone_number',
            field=models.CharField(max_length=30, null=True, verbose_name='Телефон салона'),
        ),
    ]
